name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  H_SOURCE_PDF: booklet_no_bleed.pdf
  H_TARGET_PDF: booklet_home_print.pdf
  P_SOURCE_PDF: booklet_with_bleed.pdf
  P_TARGET_PDF: booklet_professional_print.pdf
  OUT_PATH: out

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: booklet-pdfs
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "$OUT_PATH/$P_TARGET_PDF"
          generate_release_notes: true
