name: Create Release Version

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  H_TARGET_PDF: booklet_home_print.pdf
  P_TARGET_PDF: booklet_professional_print.pdf

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.P_TARGET_PDF }}
          generate_release_notes: true
